#ifndef MYENUMS_H
#define MYENUMS_H



enum MetaCommandResult{ META_COMMAND_SUCCESS, META_COMMAND_UNRECOGNIZED_COMMAND};  
enum PrepareResult{ PREPARE_SUCCESS, PREPARE_UNRECOGNIZED_STATEMENT };
enum StatementType{ STATEMENT_INSERT, STATEMENT_SELECT };
    

#endif
