#ifndef MYENUMS_H
#define MYENUMS_H



enum MetaCommandResult{ META_COMMAND_SUCCESS, META_COMMAND_UNRECOGNIZED_COMMAND,META_BEGIN_TRANS,META_COMMIT_SUCCESS};  
enum PrepareResult{ PREPARE_SUCCESS, PREPARE_UNRECOGNIZED_STATEMENT };
enum executeResult{ EXECUTE_SUCCESS, EXECUTE_UNRECOGNIZED_STATEMENT, EXECUTE_MAX_ROWS};
enum StatementType{ STATEMENT_INSERT, STATEMENT_SELECT,STATEMENT_MODIFY,STATEMENT_DELETE,STATEMENT_SELECT_ID, STATEMENT_UNRECOGNIZED};
enum PageType{ PAGE_TYPE_INTERIOR=0, PAGE_TYPE_LEAF=1,PAGE_TYPE_TRUNK=2};

#endif