#ifndef MYENUMS_H
#define MYENUMS_H



enum MetaCommandResult{ META_COMMAND_SUCCESS, META_COMMAND_UNRECOGNIZED_COMMAND};  
enum PrepareResult{ PREPARE_SUCCESS, PREPARE_UNRECOGNIZED_STATEMENT };
enum executeResult{ EXECUTE_SUCCESS, EXECUTE_UNRECOGNIZED_STATEMENT, EXECUTE_MAX_ROWS};
enum StatementType{ STATEMENT_INSERT, STATEMENT_SELECT,STATEMENT_MODIFY,STATEMENT_DELETE};
enum PageType{ PAGE_TYPE_INTERIOR=0, PAGE_TYPE_LEAF=1};

#endif